### ISSUE TITLE
"Number of first example" field is overwritten with illegal values

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#19]
Using moodle v3.3.1 20170714
and mod_checkmark v3.3.2 2017081002

We encountered this issue before upgrading to the latest version of mod_checkmark. I thought an upgrade might fix this, but it didnt. We were running a build from mid-2016 before this, so the activity was originally created with an older version.

Somehow, illegal values that probably were set in other fields seem to have "spilled over" into the field "number of first example". Once this happens, it becomes impossible to change any settings for the activity in Moodle, since Moodle will neither re-accept these values nor let you change them via the interface. We had to directly delete the value from the database in order to be able to change any settings for this activity.

Screenshot showing the illegal values in "number of first example":
![image](https://user-images.githubusercontent.com/13886080/31224402-053b0f36-a9ce-11e7-8b55-fb71d1058edf.png)

It is not actually possible to set such values via the interface, the probably "spilled over" from poorly sanitized inputs in another field:
![image](https://user-images.githubusercontent.com/13886080/31224430-24031670-a9ce-11e7-939c-6d331c472c37.png)

Like I already wrote in the other issue I posted, this plugin is giving us more trouble than any other one we ever installed on our site, and I regret not uninstalling it after the first serious issue we encountered in 2015. Now we have plenty of teachers using it in a new semester, and we face the decision of either porting all their checkmark activities to multiple choice tests or similar workarounds, or just accepting that we might face other unexpected bugs.

**Comment by kaspot** [comment]
Thanks for reporting this issue. If it was because of a migration from an older version and you already changed/deleted all the bad entries via the DB, I am not sure if there is anything to fix. Especially if we don't know what the real reason for this misbehavior was. 
Neither way we will still take a look at the code to ensure that the misbehavior is not included in the newest code of this plugin.
In order to do this may I ask you to tell us what you exactly deleted in the DB? The reference field is not directly written to the DB but is only used to create the examples (those are written into the examples table) - after this, the value of the field is re-calculated again (out of the example names). 
Can you recall with which values you have created the activity? This information would help us in trying to solve this issue.
It's too bad that you are encountering problems with this plugin. Especially the Vienna University of Technology is using this plugin since it's first days in 2007 and although there have been some issues (sometimes you just can't avoid bugs from occurring), we couldn't imagine a moodle installation without it anymore.

**Comment by stemiwe** [comment]
it was the field "name" in the table "mdl_checkmark_examples"

![image](https://user-images.githubusercontent.com/13886080/31381434-ca7f0448-adb4-11e7-9cf2-b89b05a5a9ca.png)

**Comment by kaspot** [comment]
Hi, thanks for the details. Our developer is already working on this issue.

**Comment by mkemmerling** [comment]
Fixed in v3.3.3.
