### ISSUE TITLE
exporting mod_checkmark results to PDF is sometimes formatted wrong

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#21]
Using moodle v3.3.1 20170714
and mod_checkmark v3.3.2 2017081002

Exporting the results of a checkmark activity into PDF formats the columns in a way that results in an unusable PDF:
![image](https://user-images.githubusercontent.com/13886080/31438939-93716302-ae8a-11e7-8148-0843c835fedb.png)

This is with "Submissions shown per page" set to "Optimal" and"Orientation" set to "Landscape". Any setting for "Text size" will result in similar behaviour. Setting "Submissions shown per page" to a higher count manually doesnt help either. Changing the orientation to "Portrait" results in yet another unusable printout:
![image](https://user-images.githubusercontent.com/13886080/31439089-2d7ceb38-ae8b-11e7-8c10-75f5672d3d67.png)

Exporting in Excel works, however it would make things much easier for our users if you used "1" instead of "X" for a checked activity in Excel.

**Comment by kaspot** [comment]
Thank you for reporting this, we are always glad to get feedback and recommendations on how we can improve our modules. We will do our best to also improve the table view, but because of the huge amount of columns, it is hard to find the perfect solution for every possibility.

**Comment by kaspot** [comment]
And concerning the "1" in the table view. You can use the checkmark report which will give you an even better option - it will show you the correct points per example as shown in the screenshot. Would that solve you feature wish?
<img width="964" alt="screen shot 2017-10-19 at 10 49 16" src="https://user-images.githubusercontent.com/1519714/31762425-716c8f20-b4bb-11e7-8391-6936294f3c1f.png">

**Comment by phager-at** [comment]
Hi,

it's been a while since testing needed some time.
We got a new feature in v3.3.4: Export-Templates! These offer a reliable way to get a readable PDF (as long as there are not too many examples set in the Checkmark instance.
And another improvement concerns the broken PDFs, where some columns might get displayed extremely wide and others are too small to be noticable. We now use only a relative width for each column (all columns will span the page, but the widths we predefined now only determines what percentage the columns get assigned). In the past we used a more complex system to calculate the widths (a mix of relative and absolute widths) causing the problems if there is not enough space left for the relative-width-columns.

And if you still feel the columns are too narrow to be usable, you can always try to export multiple lists with way less columns displayed (i.e. try to hide some example-columns in the exported PDF and export a second one with these previously hidden example-columns).

We want to thank you again for reporting found bugs, and we are eager to always improve the plugins usability!

Cheers,
Philipp
