### ISSUE TITLE
entering an invalid value for "Submissions shown per page" results in breaking the boost theme

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#22]
Using moodle v3.3.1 20170714
and mod_checkmark v3.3.3

One of our teachers could not show results for any checkmark activity any more, he just got a blank page with a broken menu bar:
![image](https://user-images.githubusercontent.com/13886080/31890000-f9686b8a-b801-11e7-97b7-63a9ce7bdba3.png)

After looking in the database, we saw that this user had set the checkmark_perpage to "10001000100".

The problem can be reproduced by entering this value for "Submissions shown per page" and can afterwards only be fixed by directly deleting the invalid value in the database.

I can only restate that as an admin I deeply regret ever touching this plugin - now I cannot uninstall it because too many users are using it, but I never had any moodle plugin, yet alone one by the AMC, giving me that much trouble as an admin. 

PLEASE LEARN TO SANITIZE YOUR DATABASE INPUTS!
https://xkcd.com/327/

**Comment by kaspot** [comment]
Hi and once again thank you for reporting bugs to us with in-depth detail — in this way we have always an easier time fixing them. So with this particular bug, it seems that this is a combination of moodle core and checkmark issues. Moodle core doesn’t solve this issue in the tablelib.php file because assignments are strictly limited to Alle, 10, 20, 50, 100 values, without having the option to chose their own number. We wanted to avoid limiting the number because everyone should be able to create his or her own perfect table view for checkmarks. But you are right, we should always be thinking of crazy users who do crazy stuff. We will think of a specific limitation and fix the code.
Once again thanks for reporting this and sorry to hear that you are not satisfied with this plugin. Thankfully it seems to be working fine and as expected on most of the other installations we know about.
Please let us know if you find other issues - we are more than eager to fix them as soon as possible.
Regarding this particular bug, our developer is already on it.

**Comment by mkemmerling** [comment]
Fixed in version 3.3.4.
