### ISSUE TITLE
improvement suggestion: make checked/unchecked boxes easier readable in submission table

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#29]
v3.5 has greatly improved the way in which examples are shown in the submission table - now there are individual columns for all the examples, each with an ☐ or ☒ for unchecked / checked examples.

this is way better than it was pre-v3.5, however, some of our teachers still find the ☐ / ☒ hard to read. 

would it be possible to make those boxes bolder, bigger, or in different colors (eg. red / green)?

that would be awesome :)

**Comment by stemiwe** [comment]
i just did it myself by changing lines 69-72 in locallib.php to this:

    const EMPTYBOX = '<div style="color:red; font-size:30px; margin-top:-15px; margin-bottom:-15px;"><i class="fa fa-square-o"></i></div>';
    const CHECKEDBOX = '<div style="color:green; font-size:30px; margin-top:-15px; margin-bottom:-15px;"><i class="fa fa-check-square"></i></div>';

i like the result :)

![image](https://user-images.githubusercontent.com/13886080/45875746-e5a0cf00-bd98-11e8-8dac-3da876c3f53d.png)

**Comment by phager-at** [comment]
Hi,

sorry for not commenting earlier! We haven't changed the look by now, due to a new feature currently in development, which will make a change in the look necessary.
I'm glad you found a way to simply adapt it to your needs!

cheers,
Philipp

**Comment by goggo24** [comment]
As Philipp mentioned, we are just working on a new feature. This feature will allow teachers to cross examples of a student/change the assignment in a checkmark instances. To be able to understand who checked the examples, we will redesign the look and use the color for highlighting changes by the teacher. That's why i close this issue, because we won't change it, the way you suggested. 
Be curious about the new feature ;)
