### ISSUE TITLE
Active user/group overrides are not displayed in the overrides menu

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#37]
The user/group overrides feature does not seem to have any way to show what overrides have already been set.

Even after an override is set, opening the overrides menu again only displays the option to add a new override, and does not show the existing overrides.

Also, overridden dates should not be shown striked out for users accessing the module - only the active date should be shown (like in quiz or assignment modules overrides).

Ideally, the interface and functionality should be copied from the Moodle quiz or assignment plugin, which would also improve UI consistency.

**Comment by goggo24** [comment]
We chose a different approach, because at the time of the implementation, the core functionalities were not fully developed too. Currentlyt overrides in the checkmark are indicated by the clock icon in the table. 
![clock](https://user-images.githubusercontent.com/16721900/63799316-2c356c80-c90c-11e9-8f87-70957389fad5.png)
You are right, it's not optimal. At the moment we work on a big feature and cannot estimate, when we will finish it and if we even find time to change this. If you would provide a pull request (functionality as assignment), we would be happy to accept it.

**Comment by goggo24** [comment]
Update: for our v.3.9.0 we planned to map the same behaviour for overrides as in assignment :)

**Comment by stemiwe** [comment]
cool :)

**Comment by goggo24** [comment]
implemented since v.3.9.0+
