### ISSUE TITLE
When "Due date" is disabled and "Cut-off date" enabled, display cut-off date as due date

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#43]
Currently (v3.7.0), this situation shows no end date to the students, although the cut-off date still enforces the "end of the submission period" (as described in the pop-up help).

Workaround: Also enable the due date and set it to the cut-off date.

**Comment by goggo24** [comment]
Thanks for your feedback. The behavior of availability works as in the activity assignment - so we won't change it. 
The cut-off date is never shown to students, because they shouldn't be informed, that a late delivery is even possible. If you want to set a "hard" deadline for students, you have to use both settings. 
In the pop-up help it says, that it marks the end of the submission period, but it doesn't mean that it's shown to students. Maybe we can adapt the language string, so that it's clear for teachers - do you have a suggestion for us?

**Comment by jondo** [comment]
I understand.
Like #44, this is also covered by https://tracker.moodle.org/browse/MDL-66791:
> Many of our teachers assume that they only have to set the cutoff date - this leads to assignments that are not correctly displayed to students in their calendars.
> [...]
> Improvement suggestion:
> * Make the cutoff-date setting only visible once a due date is set
