### ISSUE TITLE
Auto-adapt cut-off date to due date

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#44]
Currently, when the cut-off date is earlier than the due date, an error message is displayed:
![image](https://user-images.githubusercontent.com/21648/65241350-9b554980-dae3-11e9-8afc-e1e2e96dc22c.png)

I suggest automatically setting the cut-off date to the due date instead, accompanied by a warning that this has happened.

**Comment by jondo** [comment]
This save a lot of editing when one wants to always have the cut-off at the due date.

**Comment by stemiwe** [comment]
to be fair, this is just as clumsy in the moodle assignment plugin, which should be the standard for plugins to copy.

i just created a MDL issue to have this improved - you can see it and vote on it here: https://tracker.moodle.org/browse/MDL-66791

**Comment by jondo** [comment]
@webers-technikum-wien, you are right. Thank you for filing that issue - I have voted for it.

**Comment by goggo24** [comment]
From v3.7. it is possible as an administrator to set defaultsettings for the availability in a checkmark instance, e.g. cut-off date is two weeks after due date or set the cut-off date as the due date.
I think it's okay, that the user gets an error message in the described case =>  if we would override it automatically without a note, the teacher wouldn't notice it otherwise and he/she has to change it anyway. 
We will observe the moodle tracker issue (MDL-66791) - if there will be a change in assignment, we will probably change/install it in our own plugin too.

**Comment by jondo** [comment]
> From v3.7. it is possible as an administrator to set defaultsettings for the availability in a checkmark instance, e.g. cut-off date is two weeks after due date or set the cut-off date as the due date.

Thank you, for this useful hint!
