### ISSUE TITLE
Do not warn at 'grade automatically' when there are no former grades nor feedback

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#50]
In the Submissions tab, when I select `Ungraded` from `Bulk processing`, directly followed by `grade automatically`, there should be no warning `The former grades will be overwritten.`, because there are no former grades. Also, the warning `The former feedback will be overwritten.` should only be given if there actually is former feedback.

Currently, you are training people to ignore warnings, which is a Bad Thing™.

**Comment by goggo24** [comment]
Thanks for your feedback.  At the moment our resources are completely planned. If you can provide a pull request, we are willing to merge it back. 
Nevertheless I will include it in our backlog, but with low priority, because it's not a bug and doesn't restrict the use. So we can discuss it within the AMC when we have again resources and higher priority issues are done. I will come back later with our decision.

**Comment by jondo** [comment]
I understand, thank you. I cannot provide a pull request, so of course you're free to prioritize however you want.

**Comment by goggo24** [comment]
Included in v.3.11.2 - have fun!
