### ISSUE TITLE
Export page: buttons should stay active after export

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#63]
In the Export page, after doing an export both the `export` and the `Update data preview` buttons become inactive. They should stay active - or at least become active again after any of the corresponding "Data settings" resp. "Export settings" are changed.
As workaround I reload the page.

(Using Moodle 3.9)

**Comment by goggo24** [comment]
Thanks for reporting. I can reproduce the bug and will put it in our backlog. Eva

**Comment by phager-at** [comment]
https://git.in.moodle.com/moodle/moodle/blob/master/lib/upgrade.txt#L407 could be helpful here!

**Comment by goggo24** [comment]
Thanks Philipp ;) We will take a look on it.

**Comment by bin-der-daniel** [comment]
Dear @jondo,

thanks for reporting. This behavior is caused by a double submit protection that was implemented in moodle core in moodle 3.9. It essentially disables all submit buttons on a page after one was pressed while awaiting a page reload. However as the page isn't reloaded after the download, they are staying disabled. Fortunately there is a way to disable said behavior which I am currently integrating into checkmark.

Yours,
Daniel

**Comment by goggo24** [comment]
Included in v.3.11.2 - have fun!
