### ISSUE TITLE
0 checked examples and 0 grades

### ISSUE THREAD

**Issue by taraghi** [academic-moodle-cooperation/moodle-mod_checkmark#68]
There is a bug in view.php  as follows (reproducible as soon as the cut-off date is due):

```
You've checked 0 out of XX examples.
(0 out of a maximum of XX points)
```

Although the user has checked already some examples und has been graded for that.

To reproduce:
- create a checkmark activity in a course
- set due date and cut-off date in future
- log in as a student and check some examples
- either wait until the cut-off date is reached or (to simulate) log in as admin und reduce the cut-off date to a timestamp in the past.
- log in as the student again and open the checkmark activity => you will see the message that you `have checked 0 out of 10 examples`

**Comment by goggo24** [comment]
Thanks for reporting - we could reproduce the bug and will include the fix in the next minor version.

**Comment by bin-der-daniel** [comment]
Hallo @taraghi,

thanks for your report. After checking the issue on multiple versions, I figured out that it is not appearing anymore from Moodle 3.10 onwards. It was a side effect of fixing a broken display of presentation grades. Therefore we would suggest to update to moodle >=3.10 in order to fix this issue. Also I will update the changelog in the next version so it addresses that fix correctly.

Yours,
Daniel
